version: "3"

services:
  frontend:
    build: ./frontend
    restart: always
    container_name: container_frontend
    ports:
      -3000:3000
    networks:
      - rede-2
    volumes:
      -./frontend/src:/app/src
    depends_on:
      - backend
  backend:
    build: ./backend
    restart: always
    container_name: container_backend
    environment:
      - MYSQL_HOST: database
      - MYSQL_PORT: 3003
      - MYSQL_USER: root
      - MYSQL_PASSWORD: root
      - DB_NAME: database
    volumes:
      - ./backend/src:/app/src
    networks:
      - rede-1
      - rede-2
    ports: 
      - 3002:3002
    depends_on:
      - database
  database:
    image: mysql
    restart: always
    container_name: database
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    networks:
      - rede-1
    ports:
      - 3003:3003

networks:
  rede-1:
  rede-2:
